[package]
name = "i3ipc"
version = "0.2.0"
authors = ["Trevor Merrifield <trevorm42@gmail.com>"]
description = "A library for controlling i3-wm through its IPC interface"
license = "MIT"
repository = "https://github.com/tmerr/i3ipc-rs"

[dependencies]
unix_socket = "*"
byteorder = "*"
serde = "*"
