[package]
name = "i3ipc"
version = "0.7.0"
authors = ["Trevor Merrifield <trevorm42@gmail.com>"]
description = "A library for controlling i3-wm through its IPC interface"
license = "MIT"
repository = "https://github.com/tmerr/i3ipc-rs"

[dependencies]
unix_socket = "0.4.5"
byteorder = "0.3"
log = "0.3.7"
serde_json = "0.6.0"

[features]
i3-4-12 = []
i3-4-13 = ["i3-4-12"]
i3-4-14 = ["i3-4-13"]
i3-next = ["i3-4-14"]
dox = ["i3-next"]
