[package]
name = "i3ipc"
version = "0.3.0"
authors = ["Trevor Merrifield <trevorm42@gmail.com>"]
description = "A library for controlling i3-wm through its IPC interface"
license = "MIT"
repository = "https://github.com/tmerr/i3ipc-rs"

[dependencies]
unix_socket = "0.4.5"
byteorder = "0.3"
serde = "0.6.0"
serde_json = "0.6.0"
